---
title: "CH04製表試作"
author: "Sau-Chin Chen"
output: html_document
---

#### Questions to be solved:
**1.Rstudio 0.99無法正確讀取中文資料**  
**2.UTF-8資料轉換有問題**

1. 讀取資料。
```{r readdata, message=FALSE, warning=FALSE, results='hide', cache=TRUE}
dta <- read.table("data/bully_big5.txt", header = TRUE, encoding = "CP950")
dta_f <- subset(dta, dta[,'性別'] == '女')
dta_m <- subset(dta, dta[,'性別'] != '女')
```

2. 製作表格內容。
```{r making,  message=FALSE, warning=FALSE, results='hide', cache=TRUE}
T41f <- rbind(
c(" "," "," "," "),
round(summary(lm(憂鬱~指數+年齡,data=dta_f))$coef[2,],digits=3),
round(summary(lm(被霸凌~指數+年齡,data=dta_f))$coef[2,],digits=3),
round(summary(lm(憂鬱~被霸凌+年齡,data=dta_f))$coef[2,],digits=3),
round(summary(lm(憂鬱~指數+被霸凌+年齡,data=dta_f))$coef[2,],digits=3)
)
T41m <- rbind(
c(" "," "," "," "),
round(summary(lm(憂鬱~指數+年齡,data=dta_m))$coef[2,],digits=3),
round(summary(lm(被霸凌~指數+年齡,data=dta_m))$coef[2,],digits=3),
round(summary(lm(憂鬱~被霸凌+年齡,data=dta_m))$coef[2,],digits=3),
round(summary(lm(憂鬱~指數+被霸凌+年齡,data=dta_m))$coef[2,],digits=3)
)
```

3. 輸出表格。
```{r output, warning=FALSE, message=FALSE, results='asis', cache=TRUE}
rownames(T41f) <- c("青少年女性","1.體質指數->憂鬱", "2.體質指數->被霸凌", "3.被霸凌經驗->憂鬱", "4.體質指數->憂鬱")
rownames(T41m) <- c("青少年男性","1.體質指數->憂鬱 ", "2.體質指數->被霸凌 ", "3.被霸凌經驗->憂鬱 ", "4.體質指數->憂鬱 ")
knitr::kable(rbind(T41f,T41m), type = "html", floating = FALSE)
```

