---
title: "CH04製表試作"
author: "陳紹慶"
output:
  html_document:
    toc: yes
---

1. 讀取資料。讀入中文字無法判讀
```{r readdata, message=FALSE, warning=FALSE, results='hide', cache=TRUE}
dta <- read.table("data/bully_big5.txt", header = TRUE, encoding="CP950")
dta_f <- subset(dta, dta[,1] == levels(dta[,1])[1])
dta_m <- subset(dta, dta[,1] != levels(dta[,1])[1])
```

2.檢視資料。無法正確顯示中文資料
```{r viewdata, message=FALSE, warning=FALSE, results='asis', cache=TRUE}
knitr::kable(head(dta_f))
```


3. 製作表格內容。只能以index截取變項
```{r making,  message=FALSE, warning=FALSE, results='hide', cache=TRUE}
T41f <- rbind(
c(" "," "," "," "),
round(summary(lm(dta_f[,2]~dta_f[,4]+dta_f[,5],data=dta_f))$coef[2,],digits=3),
round(summary(lm(dta_f[,3]~dta_f[,4]+dta_f[,5],data=dta_f))$coef[2,],digits=3),
round(summary(lm(dta_f[,2]~dta_f[,3]+dta_f[,5],data=dta_f))$coef[2,],digits=3),
round(summary(lm(dta_f[,2]~dta_f[,4]+dta_f[,3]+dta_f[,5],data=dta_f))$coef[2,],digits=3)
)
T41m <- rbind(
c(" "," "," "," "),
round(summary(lm(dta_m[,2]~dta_m[,4]+dta_m[,5],data=dta_m))$coef[2,],digits=3),
round(summary(lm(dta_m[,3]~dta_m[,4]+dta_m[,5],data=dta_m))$coef[2,],digits=3),
round(summary(lm(dta_m[,2]~dta_m[,3]+dta_m[,5],data=dta_m))$coef[2,],digits=3),
round(summary(lm(dta_m[,2]~dta_m[,4]+dta_m[,3]+dta_m[,5],data=dta_m))$coef[2,],digits=3)
)
```

4. 輸出表格。行名稱的中文內容無法正確輸出，以英文取代。
```{r output, warning=FALSE, message=FALSE, results='asis', cache=TRUE}
library(xtable)
#rownames(T41f) <- c("青少年女性","1.體質指數->憂鬱", "2.體質指數->被霸凌", "3.被霸凌經驗->憂鬱", "4.體質指數->憂鬱")
#rownames(T41m) <- c("青少年男性","1.體質指數->憂鬱 ", "2.體質指數->被霸凌 ", "3.被霸凌經驗->憂鬱 ", "4.體質指數->憂鬱 ")
rownames(T41f) <- c("Teenage Girls","1.Indeces->Depress", "2.Indeces->Bully", "3.Bully->Depress", "4.Indeces->Depress")
rownames(T41m) <- c("Teenage Boys","1.Indeces->Depress ", "2.Indeces->Bully ", "3.Bully->Depress ", "4.Indeces->Depress ")
knitr::kable(rbind(T41f,T41m), type = "html", floating = FALSE)
```
